### ISSUE TITLE
Setup near.org domains

### ISSUE THREAD

**Issue by kcole16** [near/devx#154]
### TODOs
**Setup new domain and permanent redirect old domain**
- [x] docs.nearprotocol.com -> docs.near.org
- [x] examples.nearprotocol.com -> examples.near.org
- [x] [Explorer](https://github.com/near/near-explorer/issues/271)

**Setup new domain and keep old domain active**
- [x] RPC
  - [x] rpc.nearprotocol.com -> rpc.near.org
  - [x] rpc.mainnet.nearprotocol.com -> rpc.mainnet.near.org
  - [x] rpc.testnet.nearprotocol.com -> rpc.testnet.near.org
  - [x] rpc.betanet.nearprotocol.com -> rpc.betanet.near.org
  - [x] rpc.devnet.nearprotocol.com -> rpc.devnet.near.org
- [x] [Wallet](https://github.com/nearprotocol/near-wallet/issues/542)

**Comment by chadoh** [comment]
Still missing:

- RPC subdomains
- redirects from `docs`, `examples`, and `explorer` (all live at `near.org` but not redirecting from `nearprotocol.com` yet)

**Comment by frol** [comment]
@ailisp I added all the domains for *.near.org. Can you setup HTTPS for RPC subdomains and also configure HTTPS redirects for all the *.nearprotocol.com domains to the relevant *.near.org ones?

**Comment by chadoh** [comment]
Visiting rpc.mainnet.near.org directly in my browser gives a certificate warning. Is this expected?

**Comment by ailisp** [comment]
> Visiting rpc.mainnet.near.org directly in my browser gives a certificate warning. Is this expected?

Fixed now
