### ISSUE TITLE
Migrate from Studio to Gitpod (V1)

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#43]
This is considered "done" when
- [x] dependencies in examples are autoupdated https://github.com/near/devx/issues/42
- [x] near.dev lands on examples page https://github.com/near/devx/issues/36
- [x] all the examples run in gitpod and locally https://github.com/near/devx/issues/38
- [x] documentation doesn't have links to studio https://github.com/near/devx/issues/44
- [x] all the READMEs are updated https://github.com/near/devx/issues/44
- [x] when the examples break, we know because of CI https://github.com/near/devx/issues/42
- [x] a grand demo has been given to the whole world! https://github.com/near/devx/issues/47
- [x] update website
- [ ] comb through Google Slides / Docs (especially ones shared publicly) for usages of Studio  https://github.com/near/devx/issues/48 and https://github.com/near/devx/issues/43#issuecomment-594106539
- [ ] a big update is posted in commonwealth with encouraged reactions https://github.com/near/devx/issues/47
- [x] Add notes to all pages that are out of date because of Studio Removal https://github.com/near/devx/issues/44
- [x] Updated consistent templates for examples https://github.com/near/devx/issues/93
- [ ] Have Gitpod start the project immediately and make consistent (also having a separate README for Gitpod) https://github.com/near/devx/issues/94

**Comment by mikedotexe** [comment]
Here's a link to how one might search for the word "studio" in the Google Slides:
https://docs.google.com/presentation/u/0/?q=studio&tgif=d

Here are some I found that will need attention:
We're going to be removing NEAR Studio links/docs and it occurred to me that there are Google Slides where this is mentioned. These are easy to duplicate and reuse for future events, so let's make sure to change them :reminder_ribbon::
Beautifully-made presentation for FoB hackathon.
https://docs.google.com/presentation/d/17v5yQuNhoZEn7t7ffiYc0fg7zvi9yK-t7cygrUGEYVY/edit#slide=id.g7df4f5fe31_0_123 (@Sherif Abushadi)
NEAR Pitch Deck
https://docs.google.com/presentation/d/1Ksao6OvUv1AZajgiJxVfB64kuRw1ZTNOfcCJ4uK3Qv0/edit#slide=id.g6514b46858_0_102
NEAR Protocol Introduction
https://docs.google.com/presentation/d/1EeE8J1hQM5Ebp78gbJYdWQ8x53FIfCSIscCa6Mj-Nmw/edit#slide=id.g6e29e371d7_0_320 (entire slide can be changed)
If it's a small usage of the text "NEAR Studio" I think we can just change it to "GitPod examples"

**Comment by mikedotexe** [comment]
Another note: here's Kendall's doc regarding the transition plan:
https://docs.google.com/document/d/1Ri0pYN7c7eScdcSmcbgjVK1HvR8gGEH_80Ac3iAmEhM/edit#

**Comment by potatodepaulo** [comment]
Demo on Monday.
