### ISSUE TITLE
Record community sentiment to develop solutions

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/devx#67]
The community provides lots of input on the type of content they do not understand, they cannot find explained, or which they would like additional information on.

NEAR and specifically, the devx team can take this sentiment and create supporting content. 

**Tasks**
* [ ] Record community sentiment in different issues
* [ ] Assign value to different input
* [ ] Assign an owner to each input
* [ ] Determine a response process
